---
databases:
  db:
    storage: postgresql
    dsn: postgresql://guillotina@localhost:5432/guillotina
    read_only: false
cache:
  driver: guillotina.contrib.redis
  updates_channel: guillotina
applications:
  - guillotina_scootermpi
  - guillotina.contrib.swagger
  - guillotina_authentication
  - guillotina.contrib.catalog.pg
  - guillotina.contrib.mailer
host: localhost
port: 8080
root_user:
  password: root
redis:
  host: redis
  port: 6379
auth_extractors:
  - guillotina.auth.extractors.BearerAuthPolicy
  - guillotina.auth.extractors.BasicAuthPolicy
  - guillotina.auth.extractors.WSTokenAuthPolicy
auth_token_validators:
  - guillotina.auth.validators.SaltedHashPasswordValidator
  - guillotina.auth.validators.JWTValidator
cors:
  allow_origin:
    - http://localhost:8080
    - http://localhost:4200
    - "chrome-extension://*"
    - "https://client.postman.co"
  allow_methods:
    - GET
    - POST
    - DELETE
    - HEAD
    - PATCH
    - PUT
    - OPTIONS
  allow_headers:
    - "*"
  expose_headers:
    - "*"
  allow_credentials: true
  max_age: 3660
jwt:
  secret: foobar
  algorithm: HS256
jsapps:
  +admin: guillotina:static/executioner